const fs = require('fs');
const path = require('path');

global.window = {};
require('./i18n/en.js');
const en = window.TRANSLATIONS.en;

const ru = {
  langName: "Русский",
  flag: "🇷🇺",
  meta: {
    title: "Samal IT-Bunker — Прилетаешь с чемоданом, через час работаешь",
    description: "Легальный статус на 3 года, 0% налог на зарубежный доход, интернет и свет без падений, и закрытый клуб на 6 человек. Остров Самал, Филиппины."
  },
  header: {
    selectLangTitle: "Выберите язык / Language",
    logoSub: "ФИЛИППИНЫ • EO 86",
    placesCount: "Осталось: <strong class=\"text-emerald-300 font-bold\">3</strong> из 6 мест",
    contactBtn: "СВЯЗАТЬСЯ →"
  },
  hero: {
    flag: "🇵🇭",
    titleMain: "АВТОНОМНЫЙ iT-БУНКЕР",
    titleSub: "ТВОЯ 3-ЛЕТНЯЯ БРОНЯ И СВОБОДА",
    badgeSolar: "Мощная 🌞Электростанция",
    badgeStarlink: "Starlink до 350 Мбит/с",
    badgeWater: "18 000L Запасов Воды",
    slide1Tag: "БЕЗРАМОЧНЫЕ ОКНА 1.2 СМ ТОЛЩИНОЙ, ПРЯМОЙ ВИД НА ОКЕАН И ВУЛКАН",
    slide1Title: "Рабочее место с панорамным остеклением и эргономичным креслом",
    slide1Room: "Мастер Студия • Окна 3х3м",
    slide2Tag: "ВИД НА МИЛЛИОН $ НА ВЫСОТЕ 265М НАД МОРЕМ",
    slide2Title: "• ПРОХЛАДА • ТИШИНА • ПОЛНАЯ АВТОНОМНОСТЬ",
    slide2Room: "SAMAL VIEW RESORT",
    slide3Tag: "МЫ РЕШАЕМ ВСЕ ВАШИ ЗАБОТЫ ПОД КЛЮЧ",
    slide3Title: "Отдыхайте и наслаждайтесь жизнью (остальное сделаем мы!)",
    slide3Room: "ROOM #6",
    callout1: "Встретим в Аэропорту",
    callout2P1: "90+- МИНУТ И ДОМА С ",
    callout2P2: "ВИДОМ НА МИЛЛИОН",
    benQuiet: "Тихо",
    benCool: "Прохладно",
    benSafe: "Вдали от войн",
    benVisa: "Виза 3 года",
    benAutonomy: "Полная автономия!"
  },
  rooms: {
    badge: "Номерной фонд",
    title: "Номера и Цены",
    sub: "Всего 6 номеров. На данный момент свободно только 3 места.",
    status: "● Статус: <strong class=\"text-white\">3 из 6 свободно</strong>",
    r1Badge: "Занят до ноября",
    r1Size: "32 м²",
    r1Title: "2-комнатные апартаменты",
    r1Desc: "Уютный номер со всем необходимым для работы с панорамным видом на миллион.",
    r1Feat1: "✓ Моторизованный стол 140 см",
    r1Feat2: "✓ Ортопедический матрас Queen",
    r1Feat3: "✓ Безлимитный Starlink до 350 Мбит/с",
    r1PriceLabel: "Стоимость:",
    r1Price: "$600",
    r1PricePer: "/мес",
    r1Btn: "Свободен",
    r2Badge: "● Свободен (1 из 2)",
    r2Size: "45 м²",
    r2Title: "VIP панорамный номер",
    r2Desc: "Прекрасный вид на самый высокий вулкан и остров Давао. Умный дом.",
    r2Feat1: "✓ Открытая терраса с гамаком",
    r2Feat2: "✓ 4K лазерный проектор",
    r2Feat3: "✓ Премиум рабочее кресло",
    r2PriceLabel: "Стоимость:",
    r2Price: "от $800",
    r2PricePer: "/мес",
    r2Btn: "Занять",
    r3Badge: "● Свободен (2 из 2)",
    r3Size: "55 м²",
    r3Title: "VIP Open Air Пентхаус",
    r3Desc: "42м² роскошных апартаментов, огромная парящая кровать, большая кухня, картина ручной работы.",
    r3Feat1: "✓ Прямой вид на море и вулкан",
    r3Feat2: "✓ Herman Miller Embody + 4K монитор",
    r3Feat3: "✓ King-size матрас King Koil",
    r3PriceLabel: "Стоимость:",
    r3Price: "от $900",
    r3PricePer: "/мес",
    r3Btn: "Занять"
  },
  tariffs: {
    badge: "Прозрачная таблица сравнения",
    title: "Сравнение Вариантов Проживания",
    sub: "Сравните реальные расходы: самостоятельная организация быта против пакетного проживания без забот.",
    tab0: "Сам",
    tab1: "Помесячно",
    tab2: "Год всё вкл ⭐",
    srvBreakfast: "Завтрак + кофе — $5/день (≈$150/мес)",
    srvBike: "Мотобайк — $160/мес",
    srvPower: "Электричество — ≈$35/мес",
    srvLaundry: "Стирка (1 раз/нед) — $15/мес",
    srvWater: "Питьевая вода — $10/мес",
    srvTransfer: "Трансфер из аэропорта — $60 (разово)",
    included: "включено",
    perMo: "/мес",
    once: "разово",
    perHr: "/час",
    c1Num: "Вариант 01",
    c1Title: "Сам организовываешь",
    c1Sub: "Базовая аренда без сервиса, все расходы отдельно",
    c1RentLabel: "Базовая аренда номера",
    c1Price: "$750",
    c1PricePer: "/мес",
    c1PriceNote: "Без фиксации цены на год",
    c1CostBreakfast: "$150/мес",
    c1CostBike: "$160/мес",
    c1CostPower: "≈ $35/мес",
    c1CostLaundry: "$15/мес",
    c1CostWater: "$10/мес",
    c1CostTransfer: "$60 разово",
    c1TotalLabel: "Итого в месяц:",
    c1Total: "$1,120",
    c1TotalPer: "/мес",
    c1TotalNote: "+ $60 трансфер разово",
    c1Btn: "Выбрать без сервиса",
    c2Num: "Вариант 02",
    c2Title: "Помесячно",
    c2Sub: "Аренда номера + свет, вода и стирка (помесячная оплата)",
    c2RentLabel: "Оплата помесячно",
    c2Price: "$850",
    c2PricePer: "/мес",
    c2PriceNote: "Без долгосрочной фиксации",
    c2CostBreakfast: "$150/мес",
    c2CostBike: "$160/мес",
    c2CostPower: "включено",
    c2CostLaundry: "включено",
    c2CostWater: "включено",
    c2CostTransfer: "$60 разово",
    c2TotalLabel: "Итого в месяц:",
    c2Total: "$850",
    c2TotalPer: "/мес",
    c2TotalNote: "+ байк/еда по желанию отдельно",
    c2Btn: "Забронировать $850/мес",
    c3Badge: "⭐ Выгоднее всего",
    c3Num: "Вариант 03",
    c3Title: "Год вперёд, всё включено",
    c3Sub: "Фиксированная цена на 12 месяцев + полный пакет сервисов",
    c3RentLabel: "Фиксированная цена за всё",
    c3Price: "$600",
    c3PricePer: "/мес",
    c3PriceNote: "Цена зафиксирована на 12 месяцев",
    c3CostBreakfast: "включено",
    c3CostBike: "включено",
    c3CostPower: "включено",
    c3CostLaundry: "включено",
    c3CostWater: "включено",
    c3CostTransfer: "$60 разово",
    c3TotalLabel: "Итого в месяц:",
    c3Total: "$600",
    c3TotalPer: "/мес",
    c3TotalNote: "Экономия $520/мес (+$6,240/год)",
    c3Btn: "Забронировать по $600/мес",
    calcToggleBtn: "Сколько стоит ваше время на быт? <span class=\"text-cyan-400 font-semibold underline underline-offset-4\">(рассчитать)</span>",
    calcTitle: "⏱️ Расчёт упущенной выгоды",
    calcSub: "Формула: <strong>Часы × ваша ставка/час = деньги, которые вы не заработали</strong>",
    calcRatePrompt: "Выберите вашу часовую ставку:",
    calcColTask: "Бытовая задача",
    calcColTime: "Время на задачу",
    calcColHours: "Часов в месяц / разово",
    calcColLoss: "Потери в деньгах",
    calcRow1Task: "🍳 Готовка завтрака",
    calcRow1TaskDesc: "Покупка продуктов + готовка + мытьё посуды",
    calcRow1Hours: "≈ 15 ч / мес",
    calcRow2Task: "🧺 Стирка и глажка",
    calcRow2TaskDesc: "Сдать в прачечную + высушить + разобрать вещи",
    calcRow2Hours: "≈ 8 ч / мес",
    calcRow3Task: "🛵 Поиск и аренда байка",
    calcRow3Hours: "≈ 3+ часа разово",
    calcRow3TaskDesc: "Переписки, залоги, приём байка",
    calcRow4Task: "🔧 ТО и ремонт байка",
    calcRow4Hours: "≈ 2 часа разово",
    calcRow4TaskDesc: "Замена масла, тормозов, шиномонтаж",
    calcRow5Task: "🚕 Такси и SIM-карта",
    calcRow5Hours: "≈ 1.5–2 часа разово",
    calcRow5TaskDesc: "Торг в аэропорту, поиск стойки связи",
    calcSummaryMonthly: "Итого ежемесячные потери на быт при",
    calcSummaryOnetime: "Разовые потери времени на старте:",
    calcTakeaway: "💡 В тарифе «Год всё включено» весь быт закрыт под ключ. Вы инвестируете это время в разработку.",
    calcCtaBtn: "Освободить своё время →",
    footnote: "* В тарифе «Год всё включено» ($600/мес) все бытовые вопросы решены: завтрак от шефа, байк, коммуналка, клининг и трансфер уже внутри. Без скрытых платежей."
  },
  autonomy: {
    badge: "Абсолютная автономность",
    title: "Ноль отключений света, ноль падений сети",
    sub: "5-кратное дублирование всех систем жизнеобеспечения на высоте 265м над уровнем моря.",
    card1Title: "Starlink до 350 Мбит/с",
    card1Desc: "Низкоорбитальные спутники. Пинг 38–45 мс до серверов в Сингапуре.",
    card2Title: "25 кВт Солнечная Станция",
    card2Desc: "14 высокоэффективных панелей + промышленные LiFePO4 аккумуляторы для круглосуточного питания.",
    card3Title: "18 000L Резервуар Воды",
    card3Desc: "Чистейшая горная вода из 80м скважины с 3-ступенчатой фильтрацией и УФ-стерилизацией.",
    card4Title: "Умный Дом и Климат",
    card4Desc: "Бесшумные инверторные кондиционеры с ионизацией, датчиками и умным светом.",
    card5Title: "Стабилизация и Защита",
    card5Desc: "Студийная защита от перепадов напряжения и промышленный молниеотвод.",
    card6Title: "Высота 265м и Безопасность",
    card6Desc: "Естественный барьер от москитов, свежий бриз на 3–4°C прохладнее побережья и полная приватность."
  },
  arrival: {
    badge: "Ноль бытовой суеты",
    title: "Встреча в аэропорту — Дома через 90 минут",
    sub: "Забудьте типичный азиатский хаос по прилёту. Мы берем на себя 100% логистики.",
    step1Num: "01",
    step1Title: "VIP-встреча в аэропорту Давао (DVO)",
    step1Desc: "Водитель встретит вас прямо у выхода с именной табличкой и поможет с багажом.",
    step2Num: "02",
    step2Title: "Готовая безлимитная SIM-карта",
    step2Desc: "Мгновенный 5G скоростной интернет прямо с терминала аэропорта.",
    step3Num: "03",
    step3Title: "Номер готов на 100%",
    step3Desc: "Охлажденный номер, застеленная постель, рабочий Wi-Fi и горячий ужин от шефа.",
    quote: "«Прилетаешь и сразу садишься работать в тот же день, без бытовых проблем.»"
  },
  services: {
    badge: "Жизнь по системе «Всё включено»",
    title: "Все рутинные заботы под одной крышей",
    sub: "Мы позаботились обо всех бытовых вопросах, чтобы вы тратили 100% энергии на результат.",
    item1Title: "Завтрак от шефа и кофе",
    item1Desc: "Свежесваренный эспрессо, тропические фрукты и полезное сбалансированное питание.",
    item2Title: "Обеды и ужины от резидента-шефа",
    item2Desc: "Индивидуальные здоровые блюда с доставкой прямо на вашу террасу.",
    item3Title: "Доставка продуктов и товаров",
    item3Desc: "Доставка свежего манго, дуриана, продуктов и аптеки прямо к вашей двери.",
    item4Title: "Тренажерный зал и спорт",
    item4Desc: "Турники, брусья, гантели, коврики для йоги и олимпийская штанга.",
    item5Title: "Мощные скутеры в комплекте",
    item5Desc: "Обслуженные, заправленные скутеры на крытой парковке.",
    item6Title: "Профессиональная эргономика",
    item6Desc: "4K мониторы, кресла Herman Miller, фильтры питания и моторизованные столы.",
    item7Title: "Персональный консьерж 24/7",
    item7Desc: "Помощь с визовыми продлениями, логистикой острова, бронированиями и поручениями.",
    item8Title: "Терапевтический массаж на вилле",
    item8Desc: "Традиционный массаж Хилот и глубокое восстановление на вашей террасе.",
    item9Title: "Фридайвинг и йога у океана",
    item9Desc: "Коралловые рифы, паддлборды и утренние дыхательные практики с видом на залив.",
    item10Title: "Экспедиции по острову",
    item10Desc: "Поездки к водопадам Хагимит, пещерам летучих мышей и диким белым пляжам.",
    item11Title: "Кибер-лаунж и настолки",
    item11Desc: "Акустическая система, кинопроектор, VR-очки и вечерние митапы у костра."
  },
  club: {
    badge: "Закрытый клуб на 6 человек",
    title: "До 2 человек на номер — Никакой толпы",
    sub: "Мы осознанно отказались от формата шумных коливингов на 20 человек ради приватности и покоя.",
    card1Num: "01 / ОТБОР",
    card1Title: "Строгий верификационный фильтр",
    card1Sub: "Только проверенные инженеры, фаундеры и авторы с доказанным опытом.",
    card1Desc: "Никаких шумных туристов или вечеринок. Взаимное уважение к тишине строго обязательно.",
    card2Num: "02 / АТМОСФЕРА",
    card2Title: "Акустическая тишина",
    card2Desc: "24/7 режим тишины в рабочих зонах. Студийная звукоизоляция и личные балконы.",
    card3Num: "03 / ОКРУЖЕНИЕ",
    card3Title: "Сильное окружение",
    card3Desc: "Обсуждайте архитектуру, прорывы в AI и запускайте глобальные проекты вместе."
  },
  reviews: {
    badge: "Опыт резидентов",
    title: "Проверено IT-специалистами на месте",
    sub: "Реальные отзывы разработчиков, сменивших суету мегаполисов на автономность у океана.",
    r1Name: "Алексей К.",
    r1Role: "Senior Backend Engineer • Ex-Fintech",
    r1Text: "«На Бали я тратил по 3 часа в день только на разборки с шумными соседями, генераторами и прачечной. На Самале Starlink летает, кондиционер питается от солнца, а моя продуктивность выросла втрое.»",
    r2Name: "Дмитрий М.",
    r2Role: "AI Startup Founder & Researcher",
    r2Text: "«Оформление визы на 3 года по EO 86 консьерж закрыл полностью под ключ. Просыпаться с видом на вулкан Апо и пить кофе на террасе — такого уровня комфорта нет нигде в Азии.»",
    r3Name: "Илья В.",
    r3Role: "Solopreneur & Mobile Architect",
    r3Text: "«Шеф готовит еду, скутер всегда заправлен, свет не мигает. Фиксированная цена на год вперед дает полное спокойствие за бюджет.»"
  },
  trust: {
    badge: "100% Прозрачность",
    title: "Видеозвонок и спидтест до любой оплаты",
    desc: "Никаких скрытых условий. Мы проводим персональный онлайн-румтур, вместе замеряем скорость Starlink, показываем ваш номер и отвечаем на любые вопросы по документам.",
    btn: "Записаться на видеотур в Telegram →"
  },
  deepDive: {
    toggle: {
      badgeClosed: "База знаний, условий и фактов",
      badgeOpen: "База знаний развернута (6 разделов)",
      openBtn: "Развернуть все факты, правила и условия (6 разделов) ↓",
      closeBtn: "Свернуть базу знаний и условия ↑"
    },
    nav: {
      legal: "🏛️ Виза EO 86 & 36 мес",
      rules: "🚫 Культура & Табу",
      location: "🏝️ Остров Самал & Природа",
      comparison: "📊 Матрица 8 стран",
      whyBest: "🏆 9 причин почему мы лучшие",
      faq: "FAQ (6 ответов)"
    },
    legal: {
      badge: "Официальный правовой статус",
      title: "Легальное проживание на 3 года и 0% налог на доход",
      sub: "Два официальных государственных пути для легальной жизни на Филиппинах без визаранов.",
      pathATitle: "Постановление Executive Order 86 (EO 86)",
      pathABadge: "Официальный статус",
      pathA1: "✓ До 3 лет непрерывного статуса резидента с правом продления",
      pathA2: "✓ 0% налог на доходы, полученные за пределами Филиппин",
      pathA3: "✓ Полное оформление консьержем без очередей в посольствах",
      pathBTitle: "Расширенный туристический статус",
      pathBBadge: "Без бюрократии",
      pathB1: "✓ Бесплатный 30-дневный въездной штамп в аэропорту",
      pathB2: "✓ Непрерывное продление на месте до 36 месяцев без выезда",
      pathB3: "✓ Продления паспортов организует наш консьерж на месте",
      militaryNote: "🛡️ Предоставляем официальную регистрацию адреса и договор для цифровых кочевников."
    },
    rules: {
      badge: "Стандарты комьюнити и кодекс клуба",
      title: "Место для своих. Прочитайте перед бронированием.",
      sub: "Мы — закрытый клуб резидентов, а не публичный туристический хостел.",
      c1Title: "Идеальный матч",
      c1Items: "• Удаленные инженеры, фаундеры, кванты, дизайнеры<br>• Людям, ценящим тишину, чистую природу и здоровье<br>• Резидентам на долгий срок (6–12 месяцев стабильности)",
      c2Title: "Не наш профиль",
      c2Items: "• Любителям ночных клубов, баров и шума<br>• Заездам на пару дней или короткий отпуск<br>• Ожиданиям сервиса 5-звездочного отеля с круглосуточным швейцаром",
      c3Title: "Строгие табу",
      c3Items: "• Агрессия или неуважение к соседям по бункеру<br>• Шантаж отзывами и токсичное общение<br>• Нарушение тишины в тихие часы",
      warning: "⚠️ Любое нарушение правил безопасности клуба ведет к немедленному расторжению договора.",
      termsTitle: "Базовые условия контракта",
      t1: "1. Срок — 12 месяцев по фиксированной ставке.",
      t1Desc: "Формат долгосрочной резиденции для тех, кто ищет стабильную базу без суеты и постоянных переездов.",
      t2: "2. Задаток — 1 месяц для бронирования номера.",
      t2Desc: "Фиксирует номер строго за вами и снимает его с показов. Задаток невозвратен при отмене.",
      t3: "3. Оплата — в день прилета (криптовалюта USDT или банк).",
      t3Desc: "Полная оплата первого периода производится в день заселения (USDT/USDC или банк)."
    },
    location: {
      badge: "География и климат",
      title: "Остров Самал: 265м над уровнем моря",
      p1: "Остров Самал расположен в защищенном заливе Давао и естественным образом защищен от тихоокеанских тайфунов горными хребтами.",
      p2: "На высоте 265 метров температура воздуха на 3–4°C прохладнее побережья, а свежий горный бриз избавляет от тропической духоты.",
      p3: "Чистейшая артезианская вода из собственной 80-метровой горной скважины.",
      p4: "Всего 30 минут до современных госпиталей, моллов Давао и международного аэропорта (DVO).",
      imgCaption: "Вид на залив Давао и вершину вулкана Апо (2,954 м)"
    },
    comparison: {
      badge: "Честное сравнение",
      title: "Samal IT-Bunker vs Мировые Хабы",
      sub: "Оценка по 16 ключевым параметрам для долгосрочной жизни и непрерывной работы IT-специалиста (шкала 1–10).",
      colCriterion: "Критерий",
      colSamal: "Твой Samal",
      c1: "Тропический lifestyle",
      c2: "Ощущение настоящего острова",
      c3: "Тишина и акустический покой",
      c4: "Надёжность работы (в объекте)",
      c5: "Энергетическая автономность",
      c6: "Резерв воды (скважина + ОО)",
      c7: "Starlink до 350 Мбит/с",
      c8: "Английский язык в стране",
      c9: "Nomad community рядом (честно)",
      c10: "Coworking ecosystem (честно)",
      c11: "Медицина (Давао рядом)",
      c12: "Городская инфраструктура",
      c13: "Slow living & Концентрация",
      c14: "Пространство и приватность",
      c15: "Long-term suitability (3 года)",
      c16: "Уникальность продукта",
      note: "* Оценка Nomad Community и Coworking намеренно ниже (4/10): наш фокус — закрытый IT-клуб на 6 человек и абсолютная тишина, а не массовый туризм."
    },
    whyBest: {
      badge: "9 ключевых причин",
      title: "Почему мы лучше любого предложения на рынке в мире",
      sub: "Факты, цифры и продуманные инженерные решения.",
      p1Title: "1. Нулевой простой инфраструктуры",
      p1Desc: "14 солнечных панелей + LiFePO4 аккумуляторы + Starlink. 100% независимость от городской электросети.",
      p2Title: "2. 18 000L запас родниковой воды",
      p2Desc: "3-ступенчатая фильтрация горной артезианской воды с УФ-обработкой и скважина 80 метров.",
      p3Title: "3. Прямой трансфер из аэропорта включен",
      p3Desc: "Прилетели, встретил водитель, и через 90 минут вы отдыхаете в охлажденном номере. Ноль торга.",
      p4Title: "4. Реальная экономия $520+/мес",
      p4Desc: "Все расходы (завтрак от шефа, байк, свет, стирка, вода) включены в один счет.",
      p5Title: "5. В разы дешевле западных аналогов",
      p5Desc: "Схожие горные резиденции в Европе или на Красном море стоят от $2,500 до $4,500/мес.",
      p6Title: "6. Виза на 3 года без визаранов",
      p6Desc: "Живите до 36 месяцев полностью легально без выезда из страны. 0% налог на зарубежный доход.",
      p7Title: "7. Выгода от фиксации цены",
      p7Desc: "Зафиксируйте цену сейчас до открытия моста Давао-Самал, после которого цены на острове вырастут на 40%.",
      p8Title: "8. Спокойное и уважительное окружение",
      p8Desc: "Всего 6 отобранных резидентов. Строгий фильтр и абсолютная тишина для глубокой работы.",
      p9Title: "9. Бонус первых резидентов",
      p9Desc: "Станьте одним из первых резидентов с бессрочно зафиксированной ставкой и доступом к инфинити-бассейну."
    },
    faq: {
      badge: "Ответы на вопросы",
      title: "Всё, что вам нужно знать",
      q1: "Почему задаток не возвращается при отмене?",
      a1: "У нас всего 6 номеров. Бронируя номер, вы закрываете его для других кандидатов со всего мира. Задаток компенсирует простой и полную подготовку номера.",
      q2: "Какие два пути по визе доступны?",
      a2: "1) Статус цифрового кочевника по Executive Order 86 с ежегодным продлением и 0% налогом на зарубежный доход.<br>2) Туристическая виза с непрерывным продлением на месте до 36 месяцев без выезда.",
      q3: "Как происходит оплата при заселении?",
      a3: "Оплата производится строго в день заселения через криптовалюту USDT/USDC или банковский перевод.",
      q4: "Можно ли заехать с парой или питомцем?",
      a4: "Пары приветствуются в VIP панорамных апартаментах и пентхаусе. Небольшие питомцы обсуждаются индивидуально при соблюдении тишины.",
      q5: "Насколько стабилен интернет в сильный шторм?",
      a5: "У нас установлены спутниковые тарелки Starlink Gen 3 с питанием от мощной 25 кВт солнечной станции. Связь и свет работают непрерывно в любую погоду.",
      q6: "Как забронировать один из 3 оставшихся номеров?",
      a6: "Напишите нам в Telegram или WhatsApp. Мы проведем онлайн-видеотур, проверим скорость сети и закрепим за вами контракт.",
      closeBtn: "Свернуть подробности ↑"
    }
  },
  finalCta: {
    urgencyBadge: "⚡ ВНИМАНИЕ: Осталось только 3 номера из 6",
    title: "Осталось только 3 свободных номера из 6",
    bonusBadge: "БОНУС ПЕРВЫМ РЕЗИДЕНТАМ:",
    bonusDesc: "Как только все 6 номеров будут забронированы на 12 месяцев, мы строим новый инфинити-бассейн на территории. При этом цена для первых резидентов фиксируется и не растет весь год.",
    tgBtn: "Заказать сейчас в Telegram →",
    waBtn: "Написать в WhatsApp"
  },
  footer: {
    line1: "SAMAL IT-BUNKER • RESIDENCE CLUB",
    line2: "Остров Самал, провинция Давао-дель-Норте, Филиппины • 265м над уровнем моря",
    line3: "© 2026 Samal IT-Bunker. Все права защищены. Постановление EO 86."
  }
};

// Tagalog translation
const tl = {
  langName: "Tagalog",
  flag: "🇵🇭",
  meta: {
    title: "Samal IT-Bunker — Dumating bitbit ang maleta, mag-code sa loob ng 1 oras",
    description: "3-taong legal na paninirahan, 0% buwis sa kita mula sa ibang bansa, Starlink at kuryente na hindi bumabagsak, at pribadong santuwaryo para sa 6 na tao. Samal Island, Pilipinas."
  },
  header: {
    selectLangTitle: "Pumili ng Wika / Language",
    logoSub: "PILIPINAS • EO 86",
    placesCount: "Natitira: <strong class=\"text-emerald-300 font-bold\">3</strong> sa 6 na puwesto",
    contactBtn: "MAKIPAG-UGNAYAN →"
  },
  hero: {
    flag: "🇵🇭",
    titleMain: "AUTONOMOUS IT-BUNKER",
    titleSub: "ANG IYONG 3-TAONG KALASAG AT KALAYAAN",
    badgeSolar: "Malakas na 🌞Solar Station",
    badgeStarlink: "Starlink hanggang 350 Mbps",
    badgeWater: "18,000L Reserba ng Tubig",
    slide1Tag: "1.2CM KAPAL NA SALAMIN, DIREKTANG TANAW SA DAGAT AT BULKAN",
    slide1Title: "Ergonomic na workspace na may panoramic na tanawin at Herman Miller upuan",
    slide1Room: "Master Studio • 3x3m Windows",
    slide2Tag: "MILLION-DOLLAR VIEW SA TAAS NA 265M MULA SA DAGAT",
    slide2Title: "• SARIWANG HANGIN • GANAP NA KATAHIMIKAN • BUONG AUTONOMYA",
    slide2Room: "SAMAL VIEW RESORT",
    slide3Tag: "SAGOT NAMIN ANG 100% NG IYONG PANG-ARAW-ARAW NA GAWAIN",
    slide3Title: "Magpahinga at tamasahin ang buhay — kami na ang bahala sa iba!",
    slide3Room: "SILID #6",
    callout1: "Kasama ang Airport Pickup",
    callout2P1: "90+- MINUTO AT NASA BAHAY NA MAY ",
    callout2P2: "TANAWING PANG-MILYONG DOLYAR",
    benQuiet: "Tahimik",
    benCool: "Malamig na Hangin",
    benSafe: "Ligtas sa Gulo",
    benVisa: "3-Taong Visa",
    benAutonomy: "Buong Autonomya!"
  },
  rooms: {
    badge: "Pagpili ng Kuwarto",
    title: "Mga Kuwarto at Presyo",
    sub: "6 na silid lamang sa kabuuan. Sa ngayon, 3 puwesto na lang ang bakante.",
    status: "● Katayuan: <strong class=\"text-white\">3 sa 6 ang bakante</strong>",
    r1Badge: "Inookupahan hanggang Nob",
    r1Size: "32 m²",
    r1Title: "2-Kuwartong Karaniwang Apartment",
    r1Desc: "Komportableng suite na kumpleto sa kagamitan para sa malalim na pokus at magandang tanawin.",
    r1Feat1: "✓ 140cm Motorized Standing Desk",
    r1Feat2: "✓ Queen Orthopedic Mattress",
    r1Feat3: "✓ Walang Limitasyong Starlink hanggang 350 Mbps",
    r1PriceLabel: "Presyo:",
    r1Price: "$600",
    r1PricePer: "/buwan",
    r1Btn: "Bakante",
    r2Badge: "● Bakante (1 sa 2)",
    r2Size: "45 m²",
    r2Title: "VIP Frameless Glass Suite",
    r2Desc: "Napakagandang tanawin ng Bulkang Apo at Davao Gulf. May integrated smart home.",
    r2Feat1: "✓ Bukas na terasa na may duyan",
    r2Feat2: "✓ 4K Laser Cinema Projector",
    r2Feat3: "✓ Premium ergonomic executive upuan",
    r2PriceLabel: "Presyo:",
    r2Price: "mula $800",
    r2PricePer: "/buwan",
    r2Btn: "Ireserba",
    r3Badge: "● Bakante (2 sa 2)",
    r3Size: "55 m²",
    r3Title: "VIP Open Air Penthouse",
    r3Desc: "42m² ng marangyang espasyo, lumulutang na king bed, kusina, at likhang-sining.",
    r3Feat1: "✓ Direktang tanaw sa dagat at bulkan",
    r3Feat2: "✓ Herman Miller Embody + 4K display",
    r3Feat3: "✓ King Koil luxury king-size bed",
    r3PriceLabel: "Presyo:",
    r3Price: "mula $900",
    r3PricePer: "/buwan",
    r3Btn: "Ireserba"
  },
  tariffs: {
    badge: "Talahanayan ng Paghahambing",
    title: "Paghahambing ng mga Opsyon sa Paninirahan",
    sub: "Ihambing ang tunay na gastusin: sariling asikaso sa araw-araw vs. all-inclusive na walang alalahanin.",
    tab0: "Sariling Asikaso",
    tab1: "Buwanan",
    tab2: "1 Taon All-In ⭐",
    srvBreakfast: "Almusal + kape — $5/araw (≈$150/buwan)",
    srvBike: "Upa sa motorsiklo — $160/buwan",
    srvPower: "Kuryente — ≈$35/buwan",
    srvLaundry: "Labada (1x/linggo) — $15/buwan",
    srvWater: "Tubig na inumin — $10/buwan",
    srvTransfer: "Airport private transfer — $60 (minsan lang)",
    included: "kasama na",
    perMo: "/buwan",
    once: "minsan lang",
    perHr: "/oras",
    c1Num: "Opsyon 01",
    c1Title: "Sariling Asikaso",
    c1Sub: "Pangunahing upa sa kuwarto na walang serbisyo, hiwalay ang lahat ng bayarin",
    c1RentLabel: "Upa sa Kuwarto",
    c1Price: "$750",
    c1PricePer: "/buwan",
    c1PriceNote: "Walang 1-taong lock sa presyo",
    c1CostBreakfast: "$150/buwan",
    c1CostBike: "$160/buwan",
    c1CostPower: "≈ $35/buwan",
    c1CostLaundry: "$15/buwan",
    c1CostWater: "$10/buwan",
    c1CostTransfer: "$60 minsan",
    c1TotalLabel: "Kabuuang Buwanang Gastos:",
    c1Total: "$1,120",
    c1TotalPer: "/buwan",
    c1TotalNote: "+ $60 transfer sa airport minsan",
    c1Btn: "Piliin nang walang serbisyo",
    c2Num: "Opsyon 02",
    c2Title: "Buwanang Plano",
    c2Sub: "Upa sa kuwarto + kuryente, tubig, at labada (buwanang bayad)",
    c2RentLabel: "Buwanang Bayad",
    c2Price: "$850",
    c2PricePer: "/buwan",
    c2PriceNote: "Walang pangmatagalang lock",
    c2CostBreakfast: "$150/buwan",
    c2CostBike: "$160/buwan",
    c2CostPower: "kasama na",
    c2CostLaundry: "kasama na",
    c2CostWater: "kasama na",
    c2CostTransfer: "$60 minsan",
    c2TotalLabel: "Kabuuang Buwanang Gastos:",
    c2Total: "$850",
    c2TotalPer: "/buwan",
    c2TotalNote: "+ opsyonal na motor/pagkain",
    c2Btn: "Ireserba sa $850/buwan",
    c3Badge: "⭐ Pinakasulit",
    c3Num: "Opsyon 03",
    c3Title: "1 Taon All-Inclusive",
    c3Sub: "Garantisadong pirming presyo sa loob ng 12 buwan + buong VIP service package",
    c3RentLabel: "1-Taong Paunang Bayad",
    c3Price: "$600",
    c3PricePer: "/buwan",
    c3PriceNote: "Pirming presyo sa loob ng 12 buwan",
    c3CostBreakfast: "kasama na",
    c3CostBike: "kasama na",
    c3CostPower: "kasama na",
    c3CostLaundry: "kasama na",
    c3CostWater: "kasama na",
    c3CostTransfer: "$60 minsan",
    c3TotalLabel: "Kabuuang Buwanang Gastos:",
    c3Total: "$600",
    c3TotalPer: "/buwan",
    c3TotalNote: "Makatipid ng $520/buwan (+$6,240/taon)",
    c3Btn: "I-lock sa $600/buwan",
    calcToggleBtn: "Magkano ang halaga ng iyong oras sa mga gawaing-bahay? <span class=\"text-cyan-400 font-semibold underline underline-offset-4\">(Kalkulahin)</span>",
    calcTitle: "⏱️ Kalkulator ng Nawalang Kita at Oras",
    calcSub: "Pormula: <strong>Oras × Rate mo bawat oras = Salaping hindi mo kinita</strong>",
    calcRatePrompt: "Pumili ng iyong rate bawat oras:",
    calcColTask: "Gawaing-bahay",
    calcColTime: "Oras na kailangan",
    calcColHours: "Oras bawat buwan o minsan",
    calcColLoss: "Nawalang pera",
    calcRow1Task: "🍳 Pagluluto ng almusal",
    calcRow1TaskDesc: "Pamimili + pagluluto + paghuhugas ng plato",
    calcRow1Hours: "≈ 15 oras / buwan",
    calcRow2Task: "🧺 Paglalaba at pamamalantsa",
    calcRow2TaskDesc: "Pagdala sa labada + pagpapatuyo + pag-aayos",
    calcRow2Hours: "≈ 8 oras / buwan",
    calcRow3Task: "🛵 Paghahanap at pag-upa ng motor",
    calcRow3Hours: "≈ 3+ oras minsan",
    calcRow3TaskDesc: "Pakikipag-usap sa ahente, deposito, pagkuha",
    calcRow4Task: "🔧 Pagpapaayos ng motor",
    calcRow4Hours: "≈ 2 oras minsan",
    calcRow4TaskDesc: "Pagpapalit ng langis, preno, vulcanizing",
    calcRow5Task: "🚕 Taxi sa airport at SIM card",
    calcRow5Hours: "≈ 1.5–2 oras minsan",
    calcRow5TaskDesc: "Pakikipagtawaran sa driver, pagbili ng SIM",
    calcSummaryMonthly: "Kabuuang nawalang buwanang kita sa gawaing-bahay sa",
    calcSummaryOnetime: "Minsanang nawalang oras sa umpisa:",
    calcTakeaway: "💡 Sa «1 Taon All-Inclusive» tariff, tanggal lahat ng abala. Magagamit mo ang oras para sa mahahalagang proyekto.",
    calcCtaBtn: "Palayain ang Iyong Oras →",
    footnote: "* Sa «1 Taon All-Inclusive» plan ($600/buwan), lahat ng gawaing-bahay ay sagot na: almusal mula sa chef, motor, kuryente, labada, at transfer ay kasama na. Walang nakatagong bayarin."
  },
  autonomy: {
    badge: "Ganap na Autonomya",
    title: "Walang Brownout, Walang Bagsak na Koneksyon",
    sub: "5-beses na engineered redundancy para sa kuryente, tubig, at internet sa 265m taas.",
    card1Title: "Starlink hanggang 350 Mbps",
    card1Desc: "Low-orbit satellite constellation. 38–45 ms ping papuntang Singapore cloud servers.",
    card2Title: "25 kW Solar Station",
    card2Desc: "14 solar panels + LiFePO4 batteries para sa 24/7 tuloy-tuloy na kuryente.",
    card3Title: "18,000L Imbakan ng Tubig",
    card3Desc: "Malinis na tubig-bukal mula sa 80 metrong balon na may 3-stage filtration at UV sterilizer.",
    card4Title: "Smart Home at Klima",
    card4Desc: "Tahimik na inverter aircon na may ionization, smart sensors, at modernong ilaw.",
    card5Title: "Proteksyon sa Kuryente",
    card5Desc: "Studio-grade voltage stabilizer at pang-industriyang lightning arrester.",
    card6Title: "265m Taas at Seguridad",
    card6Desc: "Likas na panangga sa lamok, 3–4°C mas malamig na hangin, at pribado mula sa mataong lugar."
  },
  arrival: {
    badge: "Walang Problema sa Pagdating",
    title: "Sundo sa Airport — Nasa Bahay sa loob ng 90 Minuto",
    sub: "Kalimutan ang tipikal na gulo sa pagdating sa Asya. Sagot namin ang 100% ng biyahe.",
    step1Num: "01",
    step1Title: "VIP Davao Airport Pickup (DVO)",
    step1Desc: "Sasalubungin ka ng aming drayber sa arrivals bitbit ang personalized sign.",
    step2Num: "02",
    step2Title: "Aktibadong Unlimited SIM",
    step2Desc: "Mabilis na 5G koneksyon pagkalapag pa lamang sa paliparan.",
    step3Num: "03",
    step3Title: "Kuwarto 100% Handa at Malamig",
    step3Desc: "Malamig na silid, nakalatag na kama, konektadong Wi-Fi, at mainit na pagkain mula sa chef.",
    quote: "“Dumating at magsimulang magtrabaho sa parehong araw nang walang anumang abala.”"
  },
  services: {
    badge: "All-Inclusive na Pamumuhay",
    title: "Lahat ng Routine Sagot sa Ilalim ng Isang Bubong",
    sub: "Inasikaso namin ang bawat gawain upang 100% ng iyong enerhiya ay nakatutok sa trabaho.",
    item1Title: "Almusal mula sa Chef at Kape",
    item1Desc: "Sariwang espresso, prutas, at masustansyang pagkain araw-araw.",
    item2Title: "Tanghalian at Hapunan ng Chef",
    item2Desc: "Masusustansyang lutong-bahay na ihahatid diretso sa iyong balkonahe.",
    item3Title: "Hatid ng mga Grocery at Gamot",
    item3Desc: "Pinto-sa-pintong delivery ng sariwang mangga, durian, at kailangan sa botika.",
    item4Title: "Fitness Gym at Kagamitan",
    item4Desc: "Weights, pull-up bar, dumbbells, yoga mats, at Olympic bar.",
    item5Title: "May Kasamang Motorsiklo",
    item5Desc: "Alagang-alaga at may kargang gasolina na automatic scooter sa garahe.",
    item6Title: "Pro Tech at Ergonomics",
    item6Desc: "4K monitors, Herman Miller chairs, surge-protected outlets, at standing desks.",
    item7Title: "24/7 Personal Concierge",
    item7Desc: "Tulong sa visa extension, transportasyon sa isla, bookings, at mga gawaing teknikal.",
    item8Title: "Hilot at Therapeutic Massage",
    item8Desc: "Tradisyonal na Hilot at masahe sa iyong pribadong terasa.",
    item9Title: "Freediving at Ocean Yoga",
    item9Desc: "Coral reef snorkeling, paddleboards, at ehersisyo sa umaga na nakaharap sa dagat.",
    item10Title: "Mga Ekspedisyon sa Isla",
    item10Desc: "Pagbisita sa bat sanctuaries, Hagimit falls, at mapuputing buhangin sa baybayin.",
    item11Title: "Cyber Lounge at Board Games",
    item11Desc: "High-end sound system, cinema projector, VR headset, at talakayan sa gabi."
  },
  club: {
    badge: "Eksklusibong 6-Kataong Santuwaryo",
    title: "Hanggang 2 Tao Bawat Suite — Walang Siksikan",
    sub: "Sadyang tinanggihan namin ang maingay na 20-kataong coliving para sa isang tahimik at de-kalidad na santuwaryo.",
    card1Num: "01 / PAMANTAYAN",
    card1Title: "Mahigpit na Pag-verify",
    card1Sub: "Mga lehitimong software engineers, founders, at creators lamang ang tinatanggap.",
    card1Desc: "Bawal ang maiingay na partygoers. Mandatoryo ang respeto sa katahimikan ng bawat isa.",
    card2Num: "02 / ATMOSPERA",
    card2Title: "Acoustic Silence",
    card2Desc: "24/7 katahimikan sa mga lugar ng trabaho. Studio-grade soundproofing at pribadong balkonahe.",
    card3Num: "03 / NETWORK",
    card3Title: "Mataas na Kalidad ng Komunidad",
    card3Desc: "Magbahagi ng arkitektura ng code, mag-usap ukol sa AI, at bumuo ng global na proyekto."
  },
  reviews: {
    badge: "Karanasan ng mga Residente",
    title: "Sinubukan ng mga Espesyalista",
    sub: "Tunay na feedback mula sa mga inhinyero na lumipat mula sa siyudad patungo sa katahimikan ng isla.",
    r1Name: "Alexey K.",
    r1Role: "Senior Backend Engineer • Ex-Fintech",
    r1Text: "“Dati sa Bali nauubos ang 3 oras ko araw-araw sa brownout at labada. Dito sa Samal, hindi bumabagsak ang Starlink, solar ang kuryente, at triple ang natatapos kong trabaho.”",
    r2Name: "Dmitry M.",
    r2Role: "AI Startup Founder & Researcher",
    r2Text: "“Ang 3-taong EO 86 visa ay inasikaso nang buo ng concierge. Ang paggising na nakikita ang Bulkang Apo habang nagkakape ay walang kapantay sa buong Asya.”",
    r3Name: "Ilya V.",
    r3Role: "Solopreneur & Mobile Architect",
    r3Text: "“Nakaluto na ang pagkain at handa ang motor, kaya 100% ng oras ko ay nasa code. Ang pirming presyo sa buong taon ay nagbibigay sa akin ng kapayapaan ng isip.”"
  },
  trust: {
    badge: "100% Katapatan",
    title: "Video Call at Speedtest Bago ang Anumang Bayad",
    desc: "Hindi kami humihingi ng bulag na deposito. Nag-iiskedyul kami ng live video tour, susukatin ang bilis ng Starlink nang magkasama, at sasagutin ang lahat ng tanong sa batas.",
    btn: "Mag-iskedyul ng Live Video Tour sa Telegram →"
  },
  deepDive: {
    toggle: {
      badgeClosed: "Kaalaman, Patakaran at Katotohanan",
      badgeOpen: "Bukas na Kaalaman (6 na Seksyon)",
      openBtn: "Buksan ang lahat ng katotohanan, patakaran at kondisyon (6 na seksyon) ↓",
      closeBtn: "Itiklop ang kaalaman ↑"
    },
    nav: {
      legal: "🏛️ Visa EO 86 & 36 Buwan",
      rules: "🚫 Kultura & Bawal",
      location: "🏝️ Samal Island & Kalikasan",
      comparison: "📊 8-Bansang Matrix",
      whyBest: "🏆 9 Dahilan Kung Bakit Kami Pinakamahusay",
      faq: "FAQ (6 na Sagot)"
    },
    legal: {
      badge: "Opisyal na Legal Framework",
      title: "3-Taong Paninirahan at 0% Buwis sa Dayuhang Kita",
      sub: "Dalawang opisyal na paraan ng gobyerno upang manirahan nang legal sa Pilipinas nang walang border runs.",
      pathATitle: "Executive Order 86 (EO 86)",
      pathABadge: "Opisyal na Katayuan",
      pathA1: "✓ Hanggang 3 taong tuloy-tuloy na resident visa",
      pathA2: "✓ 0% buwis sa kitang nanggagaling sa labas ng Pilipinas",
      pathA3: "✓ Buong pag-aasikaso ng concierge nang walang pila sa embahada",
      pathBTitle: "Extended Tourist Status",
      pathBBadge: "Walang Burukrasya",
      pathB1: "✓ Libreng 30-araw na entry visa stamp sa paliparan",
      pathB2: "✓ Tuloy-tuloy na extension on-site hanggang 36 buwan nang hindi umaalis",
      pathB3: "✓ Pag-aasikaso ng pasaporte ay hawak ng aming concierge",
      militaryNote: "🛡️ May opisyal na rehistrasyon ng tirahan at kontrata para sa mga digital nomad."
    },
    rules: {
      badge: "Pamantayan ng Komunidad at Kodigo",
      title: "Lugar para sa mga Nakalinya. Basahin Bago Magpareserba.",
      sub: "Kami ay isang eksklusibong residence club, hindi pampublikong party hostel.",
      c1Title: "Para Kanino Ito",
      c1Items: "• Remote software engineers, founders, quants, designers<br>• Mga taong nagpapahalaga sa katahimikan, kalikasan, at kalusugan<br>• Pangmatagalang residente na nais ng 6–12 buwang katatagan",
      c2Title: "Hindi Para Kanino",
      c2Items: "• Mga turistang naghahanap ng bar at maiingay na party<br>• Maikling pananatili na wala pang 1 buwan<br>• Naghahanap ng 24/7 hotel butler pampering",
      c3Title: "Mahigpit na Ipinagbabawal",
      c3Items: "• Agresibong pag-uugali o kawalan ng respeto sa kapitbahay<br>• Pananakot sa review at nakakalasong komunikasyon<br>• Paggawa ng ingay sa oras ng katahimikan",
      warning: "⚠️ Ang anumang paglabag sa kaligtasan ay magreresulta sa agarang pagtatapos ng kontrata.",
      termsTitle: "Pangunahing Kondisyon ng Kontrata",
      t1: "1. Termino: 12-buwang kontrata na may pirming presyo.",
      t1Desc: "Pangmatagalang tirahan para sa mga naghahanap ng matatag na tahanan nang walang palipat-lipat.",
      t2: "2. Deposito: 1-buwang security deposit para i-lock ang kuwarto.",
      t2Desc: "Inilalaan ang kuwarto sa iyong pangalan at tinatanggal sa listahan. Hindi maibabalik kung magkakansela.",
      t3: "3. Bayad: Ang balanse ay binabayaran sa araw ng pagdating (USDT / Bank).",
      t3Desc: "Ang buong bayad para sa unang yugto ay binabayaran sa araw ng check-in sa pamamagitan ng USDT/USDC o bank transfer."
    },
    location: {
      badge: "Heograpiya at Klima",
      title: "Samal Island: 265m sa Taas ng Davao Gulf",
      p1: "Matatagpuan sa protektadong Davao Gulf, ang Samal Island ay natural na protektado sa mga bagyo ng mga nakapaligid na kabundukan.",
      p2: "Sa taas na 265 metro, ang temperatura ay 3–4°C mas malamig kaysa sa baybayin, at may sariwang hangin mula sa bundok.",
      p3: "Dalisay na tubig-bukal mula sa aming 80 metrong balon sa bundok.",
      p4: "30 minuto lamang papuntang Davao City hospitals, modern malls, at Davao Airport (DVO).",
      imgCaption: "Tanawin mula sa Samal IT-Bunker patungo sa Bulkang Apo at Davao City skyline"
    },
    comparison: {
      badge: "Paghahambing sa mga Global Nomad Hubs",
      title: "Samal IT-Bunker vs. 8 Nomad Hubs",
      sub: "Sinuri sa 16 kritikal na sukatan kabilang ang kuryente, internet, katahimikan, visa, at gastos.",
      colCriterion: "Krayterya",
      colSamal: "Samal Bunker",
      c1: "Tropikal na Pamumuhay",
      c2: "Tunay na Karanasan sa Isla",
      c3: "Acoustic Silence at Kapayapaan",
      c4: "Katatagan ng Trabaho at Kuryente",
      c5: "24/7 Solar Autonomy",
      c6: "Reserba ng Tubig (Balon + UV)",
      c7: "Starlink hanggang 350 Mbps",
      c8: "Kasanayan sa Wikang Ingles",
      c9: "Nomad Community (Eksklusibo)",
      c10: "Coworking Ecosystem",
      c11: "Medikal na Pangangalaga (Davao)",
      c12: "Imprastraktura ng Lungsod",
      c13: "Slow Living at Malalim na Pokus",
      c14: "Kaluwagan at Pribasiya",
      c15: "Pangmatagalan (3 Taon)",
      c16: "Natatanging All-Inclusive Package",
      note: "* Ang score ng Nomad Community at Coworking ay sadyang 4/10: ang aming pokus ay eksklusibong 6-kataong IT santuwaryo at katahimikan, hindi mass tourism."
    },
    whyBest: {
      badge: "9 na Haligi ng Kahusayan",
      title: "Bakit Ito ang Pinakamagandang IT Setup sa Mundo",
      sub: "Mga katotohanan, datos, at walang kapantay na kaginhawahan.",
      p1Title: "1. Walang Downtime na Imprastraktura",
      p1Desc: "14 solar panels + LiFePO4 battery bank + dual Starlinks. 100% malaya sa city grid.",
      p2Title: "2. 18,000L Reserba ng Tubig-Bukal",
      p2Desc: "3-stage filtered mountain spring water na may UV treatment mula sa 80 metrong balon.",
      p3Title: "3. Kasama ang Direktang Airport Transfer",
      p3Desc: "Lumapag, salubungin ng drayber, at magpahinga sa malamig na silid sa loob ng 90 minuto. Walang tawaran.",
      p4Title: "4. Tunay na Tipid na $520+/buwan",
      p4Desc: "Lahat ng gastusin (almusal mula sa chef, motor, kuryente, labada, tubig) ay nasa isang bayarin.",
      p5Title: "5. Mas Mura Kaysa sa Kanluran",
      p5Desc: "Ang mga katulad na mountain villa sa Europa o Red Sea ay nagkakahalaga ng $2,500 hanggang $4,500/buwan.",
      p6Title: "6. 3-Taong Visa na Walang Abala",
      p6Desc: "Manatili hanggang 36 buwan nang legal nang hindi lumalabas ng bansa. 0% buwis sa foreign income.",
      p7Title: "7. Benepisyo ng Pirming Presyo",
      p7Desc: "I-lock ang iyong presyo ngayon bago magbukas ang bagong Davao-Samal bridge kung kailan tataas ng 40% ang presyo sa isla.",
      p8Title: "8. Mapayapa at May Respetong Komunidad",
      p8Desc: "6 na residente lamang. Mahigpit na pagsusuri at katahimikan para sa malalim na konsentrasyon.",
      p9Title: "9. Bonus sa mga Unang Residente",
      p9Desc: "Sumali bilang unang residente na may habambuhay na pirming presyo at access sa itatayong infinity pool."
    },
    faq: {
      badge: "Mga Madalas Itanong",
      title: "Lahat ng Kailangan Mong Malaman",
      q1: "Bakit hindi maibabalik ang deposito kapag nagkansela?",
      a1: "Dahil 6 na suite lamang ang kabuuan, ang pagreserba ay agad na nagsasara ng puwesto para sa ibang aplikante sa buong mundo. Sinasakop nito ang gastos sa paghahanda ng silid.",
      q2: "Ano ang dalawang paraan ng visa?",
      a2: "1) Digital Nomad Status sa ilalim ng Executive Order 86 na may taunang renewal at 0% buwis.<br>2) Tourist visa na pinapahaba on-site hanggang 36 na magkakasunod na buwan nang hindi umaalis.",
      q3: "Paano ang pagbabayad sa pagdating?",
      a3: "Ang pagbabayad ay kinukumpleto sa araw ng pagdating sa pamamagitan ng USDT/USDC cryptocurrency o direktang bank transfer.",
      q4: "Maaari bang magsama ng kapareha o alagang hayop?",
      a4: "Malugod na tinatanggap ang mag-asawa/magkapareha sa VIP suites. Ang maliliit na alaga ay maaaring pag-usapan basta nasusunod ang katahimikan.",
      q5: "Gaano katatag ang internet kapag may bagyo?",
      a5: "Gumagamit kami ng dual Starlink Gen 3 dishes na suportado ng 25kW solar battery system. Ang kuryente at internet ay 100% aktibo sa anumang panahon.",
      q6: "Paano magpareserba sa 3 natitirang kuwarto?",
      a6: "Magpadala ng mensahe sa Telegram o WhatsApp. Mag-aayos kami ng live video tour, susukatin ang bilis ng internet, at isisiguro ang kontrata.",
      closeBtn: "Itiklop ang Detalye ↑"
    }
  },
  finalCta: {
    urgencyBadge: "⚡ PAALALA: 3 na lamang sa 6 na suite ang natitira",
    title: "3 Kuwarto na Lamang ang Bakante sa 6",
    bonusBadge: "BONUS SA MGA UNANG RESIDENTE:",
    bonusDesc: "Sa oras na ma-book ang lahat ng 6 na suite para sa 12 buwan, magtatayo kami ng bagong infinity swimming pool. Ang iyong presyo ay mananatiling naka-lock sa buong taon.",
    tgBtn: "Mag-mensahe sa Telegram →",
    waBtn: "Mag-mensahe sa WhatsApp"
  },
  footer: {
    line1: "SAMAL IT-BUNKER • RESIDENCE CLUB",
    line2: "Samal Island, Lalawigan ng Davao del Norte, Pilipinas • 265m sa Taas ng Dagat",
    line3: "© 2026 Samal IT-Bunker. Lahat ng karapatan ay nakalaan. Nagpapatakbo sa ilalim ng Executive Order 86."
  }
};

function writeLang(code, data) {
  const content = `window.TRANSLATIONS = window.TRANSLATIONS || {};\n\nwindow.TRANSLATIONS.${code} = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(path.join(__dirname, 'i18n', `${code}.js`), content, 'utf8');
  console.log(`Saved: ./i18n/${code}.js`);
}

writeLang('ru', ru);
writeLang('tl', tl);

