import fs from 'node:fs';
import path from 'node:path';
import { parseAllArticles } from './build-sitemap.ts';
import { loadData } from './sync-data.ts';

export function regenerateLlmsTxt(): string {
  const { rooms, pricing, meta } = loadData();
  const articles = parseAllArticles();

  const currentDate = new Date().toISOString().split('T')[0];

  let content = `# Samal IT-Bunker (${meta.name}) — Autonomous Coliving & Work Haven for Digital Nomads
> Exclusive 6-resident autonomous coliving and workspace sanctuary on Samal Island, Davao Gulf, Philippines (elevation 265m). Engineered for software engineers, founders, and digital nomads requiring 100% zero-downtime power, dual Starlink satellite internet up to 350 Mbps, ergonomic workstations with 4K displays, and 0% personal tax residency support.

## Essential Facts (NAP & Core Specs)
- Brand Name: ${meta.name}
- Alternate Name: ${meta.alternateName}
- Official Website: ${meta.url}
- Location: ${meta.address.streetAddress}, ${meta.address.addressLocality}, ${meta.address.addressRegion} ${meta.address.postalCode}, Philippines
- Coordinates: ${meta.geo.latitude}° N, ${meta.geo.longitude}° E (Elevation: ${meta.geo.elevation})
- Phone / Direct Desk: ${meta.phone}
- Email: ${meta.email}
- Telegram Channel: ${meta.social.telegramChannel}
- Telegram Concierge: ${meta.social.telegramAdmin}
- WhatsApp: ${meta.social.whatsapp}
- Aggregate Rating: ${meta.aggregateRating.ratingValue}/5.0 based on ${meta.aggregateRating.reviewCount} verified resident reviews
- Total Capacity: ${meta.totalRoomsCount || 6} luxury private suites (${rooms.filter(r => r.status === 'available').length} currently available)

## Pricing & Residency Plans (Single Source of Truth)
- Short-Term / Deep Focus Passes: ${pricing.priceRange.nightly.display}
- Monthly All-Inclusive Residency: ${pricing.priceRange.monthly.display}
${pricing.plans.map(p => `- ${p.name}: ${p.priceRange} (Commitment: ${(p as any).commitment || 'Flexible'})`).join('\n')}

## Suite Inventory & Workstation Hardware
${rooms.map(r => `### ${r.name} (${r.status.toUpperCase()})
- Area: ${r.areaSqm} m² | Price: $${r.pricePerMonth}/mo ($${r.pricePerNight}/night) | Bed: ${r.bedType}
- Desk & Ergonomics: ${r.workstation.desk}, ${r.workstation.chair}
- Monitor: ${r.workstation.display}
- Connectivity: ${r.workstation.network}
- Sound Isolation: ${r.noiseLevel}
- URL Anchor: ${meta.url}#rooms`).join('\n\n')}

## Autonomous Infrastructure Metrics
- Internet: Dual Starlink Gen 3 Actuated Terminals (350+ Mbps aggregate, 55-65ms latency to Singapore) + Teltonika 5G failover (10ms switchover).
- Power: 10kW rooftop solar array + 15kWh LiFePO4 battery bank + standby silent diesel generator. 72-hour autonomous backup during heavy monsoons.
- Water: 18,000-liter multi-stage artesian mountain spring and rainwater filtration system.
- Climate: Mountain elevation (265m) delivers naturally cooler breezes (3–5°C below sea level).

## Knowledge Base & Expert Guides (Auto-Indexed Content Collections)
The following verified engineering and legal guides are available in our static multilingual repository:
`;

  // Sort articles by language then title
  const sortedArticles = [...articles].sort((a, b) => a.lang.localeCompare(b.lang));

  for (const art of sortedArticles) {
    const url = `${meta.url}${art.lang}/blog/${art.slug}/`;
    const langLabel = art.lang.toUpperCase();
    content += `- [${langLabel}] [${art.title}](${url}): ${art.description} (Published: ${art.pubDate}, translationKey: ${art.translationKey}, status: ${art.status})\n`;
  }

  content += `\n---\n*Auto-generated by Samal IT-Bunker GEO Pipeline on ${currentDate}. Content collections synchronized with Schema.org JSON-LD & sitemap.xml.*`;

  return content;
}

export function writeLlmsTxt() {
  const content = regenerateLlmsTxt();
  fs.writeFileSync(path.resolve(process.cwd(), 'llms.txt'), content, 'utf-8');
  if (fs.existsSync(path.resolve(process.cwd(), 'public'))) {
    fs.writeFileSync(path.resolve(process.cwd(), 'public/llms.txt'), content, 'utf-8');
  }
  console.log('Successfully updated llms.txt with latest articles, rooms, and specs.');
}

if (process.argv[1] && process.argv[1].endsWith('update-llms.ts')) {
  writeLlmsTxt();
}
